# Generated by Django 5.2.1 on 2025-06-09 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('otro', 'Otro')], max_length=15, verbose_name='Especie')),
                ('raza', models.CharField(max_length=70, verbose_name='Raza')),
                ('edad', models.PositiveIntegerField(help_text='Edad en años', verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10, verbose_name='Sexo')),
                ('estado_adopcion', models.CharField(choices=[('Disponible', 'Disponible para adopción'), ('adoptado', 'Adoptado'), ('en_proceso', 'En proceso de adopción')], default='disponible', max_length=15, verbose_name='Estado de adopción')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
            ],
        ),
    ]
