# Generated by Django 5.2.1 on 2025-06-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado_adopcion',
            field=models.CharField(choices=[('Disponible', 'Disponible para adopción'), ('adoptado', 'Adoptado'), ('en_proceso', 'En proceso de adopción')], default='Disponible', max_length=15, verbose_name='Estado de adopción'),
        ),
    ]
